name: wisecore
description: A flutter core project used by Wisemen. Comes with a bunch of generally useful extensions and functions.
version: 2.0.1
homepage: https://github.com/wisemen-digital/flutter-core
repository: https://github.com/wisemen-digital/flutter-core

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  # Flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  # Riverpod
  riverpod_annotation: ">=2.0.0 <3.0.0"
  hooks_riverpod: ">=2.0.0 <3.0.0"

  # Networking
  dio: ">=5.0.0 <6.0.0"

  # Storage
  shared_preferences: ">=2.0.0 <3.0.0"

  # Logging & Debugging
  sentry_flutter: ">=8.0.0 <9.0.0"

  # Misc
  onesignal_flutter: ">=5.0.0 <6.0.0"
  url_launcher: ">=6.0.0 <7.0.0"

dev_dependencies:
  # Code generation
  build_runner: ^2.4.9

  # Static analysis & linting
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  dependency_validator: ^4.0.0

  # Riverpod
  riverpod_generator: ^2.4.0

  # Splash
  flutter_native_splash: ^2.4.0

  # Routing
  auto_route_generator: ^8.0.0


flutter:
  uses-material-design: true

