name: wisecore
description: A flutter core project used by Wisemen. Comes with a bunch of generally useful extensions and functions.
version: 1.0.6
homepage: https://github.com/wisemen-digital/flutter-core
repository: https://github.com/wisemen-digital/flutter-core

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  # Flutter
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # Riverpod
  riverpod_annotation: ^2.3.5
  hooks_riverpod: ^2.5.1

  # Routing
  auto_route: ^8.1.2
  
  # Database
  isar: ^3.1.0+1

  # Data
  json_annotation: ^4.8.1

  # Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3

  # Logging & Debugging
  logger: ^2.2.0
  sentry_flutter: ^8.0.0

  # Misc
  onesignal_flutter: ^5.1.5
  url_launcher: ^6.2.6
  maps_launcher: ^2.2.1

dev_dependencies:
  # Code generation
  build_runner: ^2.4.9

  # Static analysis & linting
  flutter_lints: ^3.0.2
  custom_lint: ^0.6.4
  dependency_validator: ^3.2.3

  # Riverpod
  riverpod_generator: ^2.4.0

  # Splash
  flutter_native_splash: ^2.4.0

  # Routing
  auto_route_generator: ^8.0.0


flutter:
  uses-material-design: true
# flutter_intl:
#   enabled: true # Required. Must be set to true to activate the plugin. Default: false
#   class_name: SCoreT # Optional. Sets the name for the generated localization class. Default: S
#   main_locale: en # Optional. Sets the main locale used for generating localization files. Provided value should comply with ISO-639-1 and ISO-3166-1 (e.g. "en", "en_GB"). Default: en

